bin/download
bin/start
package.json
schema.js
utils/download_data.js

This PR adds what should be a flexible but robust downloader, currently supporting any uncompressed CSV file, but build to be able to be extended in the future to transparently handle `zip`, `gzip`, `and bzip2` files.

Add downloader for uncompressed CSV files

---

Dockerfile

The path previously contained `openaddresses`, since that's the origin of this code.
While it has no effect on functionality, this path should be updated for clarity.

fix(docker): Use correct path name for code

---

import.js
lib/parameters.js
schema.js
test/parameters.js
test/schema.js

The CSV importer is designed to be optional, and thus all config options should be optional as well.

fix(schema): Remove required keys

---

lib/importPipeline.js
package.json

Admin lookup support via [wof-admin-lookup](https://github.com/pelias/wof-admin-lookup) was omitted in the initial port of this project from the OpenAddresses importer.
Unlike the OpenAddresses importer, which added extra adminLookup configuration to disable lookups against some WOF layers (such as `marinelayer`, `ocean`, etc), this importer uses all layers to support any custom data (which may or may not be land based).

feat(import): Add admin lookup

---

import.js
lib/parameters.js
lib/streams/recordStream.js
test/streams/recordStream.js
test/test.js

This cleans up the last bits of code remaining from converting the OA importer to the CSV importer.
Fixes https://github.com/pelias/csv-importer/issues/17

chore(comments): Remove out of date references to OpenAddresses

---

lib/streams/documentStream.js

This uses the support for `cross_street` added in https://github.com/pelias/model/pull/111 and https://github.com/pelias/schema/pull/346

Add support for `cross_street` address field

---

import.js
lib/importPipeline.js
package.json

This allows distinguishing which logger output lines correspond to which importer during an import.
Unlike other importers, this PR is slightly more complicated as we have to support unique names for each of what might be several parallel sub-importers.
Dependency injection for `dbclient` was removed to facilitate this.
Connects https://github.com/pelias/dbclient/issues/101

    feat(logger): Use dbclient name functionality

---

lib/streams/documentStream.js
test/streams/documentStream.js

After this, I believe all fields are _actually_ case insensitive, which the README has promised for some time.

fix(source): Support case insensitive source field

---

README.md

This ties into the new documentation for the API in https://github.com/pelias/api/pull/1297 for functionality originally added in https://github.com/pelias/api/pull/1131.
Fixes https://github.com/pelias/csv-importer/issues/36
Fixes https://github.com/pelias/csv-importer/issues/26

feat(docs): Add custom source/layer documentation

---

package.json

As mentioned in https://github.com/pelias/openaddresses/pull/343, we were a bit nervous about a behavior change introduced in combined-stream 1.0.7.
However, as discovered in https://github.com/felixge/node-combined-stream/issues/40 it's a bugfix that makes previously unrecommended use of the library finally break.
The code in this repository is already using the library in the recommended way, and isn't affected, so we might as well stay with the latest version.
Closes https://github.com/pelias/csv-importer/pull/32

feat(deps): Use carat range for combined-stream

---

package.json

As of `pelias-config-4.8.0` we are now using the new Elasticsearch 7 compatible default document type name: `_doc`.
Now that we have dropped support for ES5, we want to ensure this value is the default going forward.
Connects https://github.com/pelias/config/pull/122
Connects https://github.com/pelias/pelias/issues/831

Require >= pelias-config-4.8.0

---

package.json

Looks like a few dependencies were missing their carat range specifiers.
We decided on this all the way back in https://github.com/pelias/pelias/issues/366
Closes https://github.com/pelias/csv-importer/pull/57

chore(deps): Use carat ranges for dependencies

---

package.json

We want to ensure the new postal cities override logic is included: https://github.com/pelias/wof-admin-lookup/pull/296.

Explicitly bump to pelias-wof-admin-lookup v7.1.0

---

README.md
lib/streams/documentStream.js
test/streams/documentStream.js

The readme suggested that `postalcode` and `zipcode` were the allowed names of fields for postal code information.
In fact, `postcode` was allowed, but _not_ `postalcode`. Now both are supported.

fix(postalcode): Support postalcode as field name

---

README.md
lib/streams/documentStream.js
test/parameters.js
test/streams/documentStream.js
test/streams/recordStream.js

The current CSV importer is very basic. We can do something much more interesting here, specially when we have custom data with many information.
OSM is a good example, when can have a tons of information like categories and multi-lang. This should be a good addition for this importer.
I added some new columns to enrich the data. Columns are:
- name_{lang}: Should be a ISO 639-1 language code, like we do with OSM
- name_json: Should be a JSON Array for the default name, this is cool for name aliases
- name_json_{lang}: Sould be a JSON Array for the specified lang
- category: A simple category to add for this entry
- category_json: A JSON Array to add many categories for an entry
Use theses new columns in your CSV and voilà.

Supports for categories, multi-lang columns and aliases

---

.travis.yml

This flag is no longer needed and causes an alarming yellow circle to appear in the Travis UI for the build config validation :)

Remove deprecated `sudo: false` TravisCI config flag

---

bin/parallel

This improves the parallel import entry point, allowing it to be used for general purposes as the OA parallel import script is, since https://github.com/pelias/openaddresses/pull/410.
Now we can use `./bin/parallel` always, and handle parallelization in places like pelias/docker

feat(parallel): Improve parallel import

---

README.md

- Connected to https://github.com/pelias/csv-importer/issues/75
In this issue I learned that for the moment, pelias csv importer does support only WGS projected data. In the user guide (README.md) of this project, I found usefull to add a comment on this specification.
---

added comment about lat and lon projection. Related to #75

---

README.md
lib/streams/documentStream.js
test/streams/documentStream.js

To make external POIs be at the baseline scoring as OSM venues, they should have some baseline popularity, since many OSM POIs have a popularity of ~2000 which makes it hard for third party chain data to compete with it
Connects https://github.com/pelias/csv-importer/issues/71

add optional popularity column to pelias csv importer

---

lib/streams/documentStream.js
test/streams/documentStream.js

I had a csv import that was silently failing because my addendum_json_XXX field was empty in some rows.
This change allows for empty values in addenum_json_XXX fields and adds a lot of tests for both that field and other json fields in csv import
In a separate change, I will attempt to print out badRecordCount somewhere, and in another I will propose we log failed rows to stderr

feat(json): Allow empty addendum json

---

lib/streams/documentStream.js
lib/streams/recordStream.js

Adds this message in stdout at the end of each csv file
`    2020-10-09T19:37:43.930Z - info: [csv-importer] Finished import from /var/folders/_d/jq4xv1d94p129cm4899l3zbc0000gn/T/csv-importer-test202099-52784-m927ct.shrvf, goodRecordCount=1 badRecordCount=0`
I beleive this will make it much easier to notice when csv files have problems

feat(logging): add a status message when a csv is done importing with good/bad counts

---

lib/streams/recordStream.js
package.json

this PR enables the [bom: true](https://csv.js.org/parse/options/bom/) config option which strips the [Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark) from files (where present).
I've coupled this change with an upgrade to the `npm csv-parse` module. [changelog](https://github.com/adaltas/node-csv/blob/master/packages/csv-parse/CHANGELOG.md)
resolves https://github.com/pelias/csv-importer/issues/89

strip byte-order-mark from CSV files

---

README.md
lib/streams/documentStream.js
package.json
test/streams/documentStream.js

:wave:
---
We have data from multiple sources with the custom data formats like NeTEx, SOSI, GeoJson, CSV etc.
In order to import that data to Pelias elasticsearch, we have decided to convert the data to single format and store it in our cloud storage which we will be importing to the Pelias elasticsearch later on.
Instead of writing aur own importer / importers,  we have decided to convert the data from all the sources to CSV and then use the `pelias-csv-importer` to import it in pelias elasticsearch. 
The `pelias-csv-importer` is somewhat limited in supporting the fields that can be imported through it, although the `pelias-model` support alot of fields. 
We want to contribute to the `pelias-csv-importer` to support more fields.
---
In this PR we are adding the support to import the …

Added support for importing parent property.
